import { Navbar, Providers } from '@components'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Open_Sans } from 'next/font/google'

const roboto = Open_Sans({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap', 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className='bg-slate-50 dark:bg-blackmain1 antialiased'>
        <Providers>
          {children}
          <Navbar />
          {/* <Footer /> */}

        </Providers>
      </body>
      {/* Allow for more hieght on mobile divices */}
      {/* <div className='h-40 md:hidden' /> */}
    </html>
  )
}
